image: node:6.9.4

pipelines:
  default:
    - step:
        name: Default step
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
          - npm run build
          - ls -la
          - find ./ -name index.html